import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import { Playfair_Display, Poppins} from "next/font/google";
import "./globals.css";


export const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600","700"],
});
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600","700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
